merchant_code = "SS64008202"
authentication_code = "aB7!tR8he9jQB"
successful_url = "https://www.cambio.co.nz/payment/success"
initiate_transaction_url = "https://api.cambio.co.nz/payment/poli"
get_transaction_url = "https://poliapi.apac.paywithpoli.com/api/v2/Transaction/Initiate"
merchant_home_page_url = "https://www.cambio.co.nz"
notification_url = "https://api.cambio.co.nz/payment/poli/nudge"
unsuccessful_url = "https://www.cambio.co.nz"
connection_string = "postgres://mate@localhost:5432/cambio_test"
web3_address = "../eth_test/data/geth.ipc"
