\i utils.sql
\i assets.sql
\i users.sql
\i ledger.sql
\i ethereum.sql
\i payments.sql
\i core.sql
\i media.sql
\i country.sql
\i profile.sql
\i order.sql
\i core_procedures.sql
\i procedures.sql
\i init_db.sql
