CREATE DOMAIN TX_HASH VARCHAR(64);
CREATE DOMAIN TX_ADDRESS VARCHAR(40);
CREATE DOMAIN ECDSA_SIGNATURE VARCHAR(260);  

CREATE TABLE outbound_transaction (
    nonce UINT NOT NULL,
    gas_price BIGINT NOT NULL,
    gas_limit BIGINT NOT NULL,
    to_address TX_ADDRESS NOT NULL,
    from_address TX_ADDRESS NOT NULL,
    value BIGINT NOT NULL,
    signature ECDSA_SIGNATURE NOT NULL
);
